version: "3.8"
services:
  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - '0M'
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - redpanda:9092
      - --advertise-kafka-addr
      - redpanda:9092
      - --set
      - 'auto_create_topics_enabled=true'
    image: docker.vectorized.io/vectorized/redpanda:v21.9.5

  tremor_in:
    image: tremorproject/tremor:edge
    depends_on:
      - redpanda
    environment:
      - SLEEP=5
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    volumes:
      - ./etc/tremor_in:/etc/tremor:ro
      - ./var/log/in:/var/log/:rw

  tremor_out:
    image: tremorproject/tremor:edge
    depends_on:
      - redpanda
    environment:
      - SLEEP=3
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    volumes:
      - ./etc/tremor_out:/etc/tremor:ro
      - ./var/log/out:/var/log:rw

