version: "3.8"
services:
  redpanda:
    command:
      - redpanda start
      - --smp=1
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id=0
      - --check=false
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr 127.0.0.1:8082
      - --kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --set auto_create_topics_enabled=true
#      - --set redpanda.developer_mode=true
    image: docker.vectorized.io/vectorized/redpanda:v21.9.3
    ports:
      - 8082:8082
      - 9092:9092
      - 29092:29092
    hostname: redpanda
    container_name: redpanda
    volumes:
      - ./var/lib/redpanda/data:/var/lib/redpanda/data

  tremor_in:
    image: tremorproject/tremor:edge
    depends_on:
      - redpanda
    environment:
      - SLEEP=5
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    volumes:
      - ./etc/tremor_in:/etc/tremor:ro
      - ./var/log/in:/var/log/:rw

  tremor_out:
    image: tremorproject/tremor:edge
    depends_on:
      - redpanda
    environment:
      - SLEEP=3
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    volumes:
      - ./etc/tremor_out:/etc/tremor:ro
      - ./var/log/out:/var/log:rw

