version: "3.8"
services:
  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - '0M'
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - redpanda:9092
      - --advertise-kafka-addr
      - redpanda:9092
    image: docker.vectorized.io/vectorized/redpanda:v21.9.5
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9644/v1/status/ready"]
      start_period: 0s
      interval: 1s
      retries: 30
  topic-creator:
    image: docker.vectorized.io/vectorized/redpanda:v21.9.5
    command:
      - topic
      - --brokers
      - redpanda:9092
      - create
      - tremor
    depends_on:
      redpanda:
        condition: service_healthy

  tremor_in:
    image: tremorproject/tremor:edge
    depends_on:
      redpanda:
        condition: service_healthy
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    volumes:
      - ./etc/tremor_in:/etc/tremor:ro
      - ./var/log/in:/var/log/:rw

  tremor_out:
    image: tremorproject/tremor:edge
    depends_on:
      redpanda:
        condition: service_healthy
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    volumes:
      - ./etc/tremor_out:/etc/tremor:ro
      - ./var/log/out:/var/log:rw

